apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-svc
  labels:
    app: my-nodeport-svc
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: / #depends on scenarios
    alb.ingress.kubernetes.io/healthcheck-port: '80' #depends on scenarios
    alb.ingress.kubernetes.io/success-codes: '200' #depends on scenarios
spec:
  type: NodePort
  selector:
    app: myapp1
  pors:
    - port: 80
      targetPort: 80
      nodePort: 31231
